### ISSUE TITLE
Notebook initialization

### ISSUE THREAD

**Issue by vangberg** [vangberg/CompThink#2]
When you first open a notebook, all cells have to run. It would be nice with some sort of indicator showing that some cells are running.

**Comment by vangberg** [comment]
Process status: https://github.com/fonsp/Pluto.jl/pull/2399

**Comment by fonsp** [comment]
Hey @vangberg !

I hope you are enjoying the computation thinking course! Your feedback is super welcome, I just found your list issues and there is some good stuff there!

You are right on the money with this one: the new feature https://github.com/fonsp/Pluto.jl/pull/2399 is being made directly based on feedback on the computation thinking course: we need to show tangible progress while the notebook is launching. I would love your feedback on https://github.com/fonsp/Pluto.jl/pull/2399. Try out the PR and send us what you think! Also be sure to read the updated notes on the PR.

I will be sure to take a closer look at your issues later, they are really useful, so keep them coming!

-fons

**Comment by vangberg** [comment]
Hi @fonsp 

Great work on the process status. I enjoy the course, and Pluto.

I am a long-time R Markdown-fan, and have been following Pluto from the sidelines for some time. Finally getting to use it has been a joy, and I am surprised how much the reactivity means for the *experience*. Programming feels fluid, and I have a hard time using other notebooks at this point.

As an example, I was exploring some data in a SQLite database the other day, and Pluto was great for that. Load the data, set up a query, show the output in a table and add a text input. Interactive MVP in a couple of minutes!

So thank you :blush: 

![image](https://user-images.githubusercontent.com/252/205009749-77cd24de-4ab7-4111-bb77-ab30ba5a9c25.png)

**Comment by vangberg** [comment]
Fixed in Pluto
